language: python

python:
#  - "3.5" TF 2.0.0b1
  - "3.6"
  - "3.7"
env:
  - TF_VERSION=2.0.0
  - TF_VERSION=2.1.0
  - TF_VERSION=2.2.0
  - TF_VERSION=2.3.0
cache: pip

# command to install dependencies
install:
  - pip install -q tensorflow==$TF_VERSION
  - pip install -r requirements.txt
  - pip install -q pytest-cov==2.4.0
  - pip install -q python-coveralls
  - pip install -q codacy-coverage
# command to run tests
script:
  - pytest --cov=deeptables

notifications:
  recipients:
    - yangjian@zetyun.com

  on_success: change
  on_failure: change

after_success:
  - coveralls
  - coverage xml
  - python-codacy-coverage -r coverage.xml
